### ISSUE TITLE
ABB Terra firmware v1.8.32 all entities unavailable

### ISSUE THREAD

**Issue by d-l-h** [lbbrhzn/ocpp#1588]
**Describe the bug**
OCPP Integration v0.8.4
When using ABB Terra wallbox with firmware v1.8.32 ([Changelog](https://library.e.abb.com/public/fe5b51020047410a80ae7e45046714f8/Release%20notes%20Terra%20AC%20FW_v1.8.32_CE_External.pdf?x-sign=AnGf5gtrebH6aWHNPTUz6zRhLqfYjYuJpk14QYjJHkUeNqShRPRe4R%2fg0uoa2A34)) all entities became unavailable.
Communication seems to be working as vendor and firmware is detected as expected. (see screenshot)

**Errors**

`Failed with response: Rejected`

`Forcing number of connectors to -1, charger returned 1`

`ValueError: Config entry central (01JPNAE3J4XBZCW13K1PMJ27E3) for ocpp.sensor has already been setup!`

<img width="662" alt="Image" src="https://github.com/user-attachments/assets/ce26a21f-3385-4e0c-802a-804f1b6b4d2b" />

**Comment by d-l-h** [comment]
Problem solved with waiting one hour. Now everything is there

**Comment by d-l-h** [comment]
I downgraded to `OCPP Integration v0.7.0` and it is working fine.

I installed `v0.8.4` as described in [Issue 1572](https://github.com/lbbrhzn/ocpp/issues/1572#issuecomment-2724452395) which was working fine with `ABB Terra firmware v1.8.21`.
But with the newer firmware I cannot get it running.

**Comment by une18** [comment]
Tested again, after 2 weeks as I can see 0.8.1.... 0.8.4 upgraded, but still the same. It does not work with my ABB Terra. 
Rolled back again  now to 0.7.0. but I am unable to get it working again. have rolled back several times without issues before...

**Comment by d-l-h** [comment]
> Tested again, after 2 weeks as I can see 0.8.1.... 0.8.4 upgraded, but still the same. It does not work with my ABB Terra. Rolled back again now to 0.7.0. but I am unable to get it working again. have rolled back several times without issues before...

Did you completely remove everything as described in [Issue 1572](https://github.com/lbbrhzn/ocpp/issues/1572#issuecomment-2724452395)?

This issue is closed, as a reboot of my ABB Terra charger fixed it. Now its working fine with firmware 1.8.32 and OCPP integration 0.8.4

**Comment by pierinho** [comment]
For me not working. Fw 1.8.32 all entities are unavailable, after reboot of wallbox.
